#!/usr/bin/env bash
set -euo pipefail

sudo apt-get update && sudo apt-get install -y tmux

# Install mise packages
mise trust
mise install

# Symlink mise.toml and mise.lock in ~/
# Allows use of mise-installled tooling from mise being activated in ~/
ln -sf "$PWD/mise.toml" "$HOME/.mise.toml" && mise trust "$HOME/.mise.toml"
ln -sf "$PWD/mise.lock" "$HOME/.mise.lock" && mise trust "$HOME/.mise.lock"
