#!/usr/bin/env bash
set -euo pipefail

sudo DEBIAN_FRONTEND=noninteractive apt-get update
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y tmux
sudo DEBIAN_FRONTEND=noninteractive rm -rf /var/lib/apt/lists/*

# Install mise packages
mise trust 2>&1
mise install 2>&1
